### ISSUE TITLE
作者进局子了？

### ISSUE THREAD

**Issue by CkBcDD** [MicroCBer/BetterCEF#304]
项目怎么都Archive了

**Comment by feng-or** [comment]
暂时避风头，隔壁的事情

**Comment by MicroCBer** [comment]
https://t.bilibili.com/763751876707483655

谢谢你，局子侠
![C63ZZ)9F_3A2Q7 1T007 _P](https://user-images.githubusercontent.com/66859419/219854904-c5f45635-f0db-4ba8-9bec-cac0db243506.jpg)
