### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Estar-dev-star** [MicroCBer/BetterCEF#305]
官方的下载渠道显示未适配，并且之前一段时间插件市场中无法显示任何插件，只有开发者选项。

**Comment by yangnuozhen** [comment]
插件市场基于的仓库因为[一些原因](https://t.bilibili.com/763751876707483655)暂时无法访问，如有下载插件需求，可以访问[此专栏](https://www.bilibili.com/read/cv21873056)，或进Q群479613101下载 `群友上传/plugins.zip` ，拷贝到`C:\betterncm\plugins`文件夹使用。

**Comment by yangnuozhen** [comment]
手动安装方法请参考[文档](https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#M04Ud8SIqo6I0YxUd4icNEmmn4c)

**Comment by f2934749636** [comment]
OK
